# Kernel
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_HEAP_MEM_POOL_SIZE=2048

# Console
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_PRINTK=y

# GPIO
CONFIG_GPIO=y
# This enables the specific STM32F1xx HAL driver files

# SPI
CONFIG_SPI=y

# CAN
CONFIG_CAN=y
## STM32 requires specific clock settings for CAN, usually handled by Zephyr
CONFIG_CAN_STATS=y

# STM32 HAL

# C++
CONFIG_CPP=y

CONFIG_STDOUT_CONSOLE=y
CONFIG_UART_CONSOLE=y

# Enable protobuf
CONFIG_NANOPB=y
